### ISSUE TITLE
裁剪后下面有黑色横线的问题

### ISSUE THREAD

**Issue by vbonluk** [CoderJackyHuang/HYBImageCliped#2]
如图：
![wechat_1459933551](https://cloud.githubusercontent.com/assets/7578155/14311416/eb12eb96-fc19-11e5-8bef-c6ae7439946a.jpeg)

调用的代码：
![dd650ede-0c91-467b-b332-f5e960d2fd9a](https://cloud.githubusercontent.com/assets/7578155/14311450/23428a76-fc1a-11e5-9077-3dd863c4a88a.png)

**Comment by vbonluk** [comment]
奇怪的是有的会出现，有的不会出现。。。

**Comment by CoderJackyHuang** [comment]
你这是异步下载图片，这时候剪裁得得到图片？另外你据说的黑线是指哪条？图中没看出来哪个线是剪裁后生成的！

**Comment by vbonluk** [comment]
头像下面有条黑线，我现在的图片是已经缓存好的了。待会我将裁剪的方法放到下载完成的block里面试试。

**Comment by vbonluk** [comment]
![wechat_1459934188](https://cloud.githubusercontent.com/assets/7578155/14311740/7a0f2124-fc1b-11e5-8d0f-fd3dbf55d625.jpeg)

正常的是这样的。用了裁剪就多了黑条

**Comment by CoderJackyHuang** [comment]
也就是说你的最后一张图片的高度是很小的，有很多个API可以剪裁，有些参数可以设置一下。比如先设置backgroundColor为白色，这样应该就可以了！

**Comment by vbonluk** [comment]
![0a967c74-8ecf-454f-ba3a-0247d65eca3a](https://cloud.githubusercontent.com/assets/7578155/14312120/65ddcdde-fc1d-11e5-935a-9ba7e0e542c9.png)
我通过这样调用，解决了黑条的问题。
谢谢

**Comment by vbonluk** [comment]
我设置了isEqualScale为NO，这里不等比例，不会有什么问题吧？

**Comment by CoderJackyHuang** [comment]
不会，因为我的图片与控件的比例差太大了，就应该设置为不等比例！
