### ISSUE TITLE
pod search 搜索不到

### ISSUE THREAD

**Issue by jinweizhao** [CoderJackyHuang/HYBImageCliped#3]
pod search HYBImageCliped
[!] Unable to find a pod with name matching `HYBImageCliped'

**Comment by CoderJackyHuang** [comment]
更新一下你的pod，现在使用的人数已经有不少了，所以一定是可以查找到的。我也在用的！

原始邮件
发件人:Will-Znotifications@github.com
收件人:CoderJackyHuang/HYBImageClipedHYBImageCliped@noreply.github.com
发送时间:2016年4月8日(周五) 14:39
主题:[CoderJackyHuang/HYBImageCliped] pod search 搜索不到 (#3)

pod search HYBImageCliped
 [!] Unable to find a pod with name matching `HYBImageCliped'

**Comment by jinweizhao** [comment]
ok了   更新了好长时间    更新前是0.39.0   更新后也是0.39.0   但是就可以搜索到了   thank  you
